### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by gabrielpessoa** [gmatheus66/OSON#2]
Eu **como** cinéfilo **quero** um sistema de autenticação **para**  ter acesso total dos conteúdos do site.

- [x] Criação do frontend;
- [x] validação de usuário;
- [x] Criação do backend;

**Comment by ranierivalenca** [comment]
Se o logout deve fazer parte desta issue, então deveria estar descrito como uma tarefa.

**Comment by gabrielpessoa** [comment]
Concluído
