### ISSUE TITLE
Criação de cadastro para usuário 

### ISSUE THREAD

**Issue by LiraGui** [gmatheus66/OSON#3]
Eu **como** cinéfilo **quero** realizar o cadastro no site **para** obter mais informações das séries e poder avaliá-las.

- [x] criação do script para inserir dados e consultar dados do usuário.
- [x] utilizar criptografia para inserção da senha
- [x]  backend da cadastro do usuário ( lembrar de consultar o cpf do usuário antes para saber se ele já está cadastrado.)
- [x]  frontend da tela de cadastro do usuário ( formulário baseado nos campos do BD)
- [x] realizar validação de senha, cpf já cadastrado, e-mail, username já cadastrado.
- [x] criação de nova coluna no banco para username.
- [x] envio de feedback de erro para página de cadastro via método GET.

**Comment by lilialnas** [comment]
Eu **como** cinéfilo **quero** realizar o cadastro no site **para** obter mais informações das séries e poder avaliá-las.
- [ ] criação do script para inserir dados e consultar dados do usuário.
 - [ ] utilizar criptografia para inserção da senha
- [ ] backend da cadastro do usuário ( lembrar de consultar o cpf do usuário antes para saber se ele já está cadastrado.)
- [ ] frontend da tela de cadastro do usuário ( formulário baseado nos campos do BD)
- [ ] realizar validação de senha, cpf já cadastrado, e-mail, username já cadastrado.

**Comment by LiraGui** [comment]
Reabertura da issue por causa de comentários no código.
